version: "3.9"

services:
  node:
    build:
      context: .
      dockerfile: ./backend/docker/node/Dockerfile
      target: production
    command:
      - "npx"
      - "webpack"
    environment:
      NODE_ENV: "development"
    restart: "no"
    volumes:
      - "./backend:/app"
    ports:
      - "8000:8000"

  react:
    build:
      context: .
      dockerfile: ./frontend/docker/node/Dockerfile
      target: production
    command:
      - "npm"
      - "run"
      - "serve"
    environment:
      NODE_ENV: "development"
    restart: "no"
    volumes:
      - "./frontend:/app"
    ports:
      - "80:3000"